---

ansible_connection: network_cli
ansible_network_os: ios
ansible_user:       admin1
ansible_password:   admin1

isis:
  state: present
  net_area:  49.0007
  metric_crosslink: 15
  metric_downlink:  1000
  metric_uplink:    100

ldp:
  state: present

bgp:
  state: present
  as: 7
