all:
  children:
    AGG:
      hosts:
        AGG18:
          services:
            2000:
              state: present
              uplink: eth1
              access: eth3
            2100:
              state: present
              uplink: eth1
              access: eth4
            3000:
              state: present
              uplink: eth1
              access: eth5
        AGG19:
          services:
            2000:
              state: present
              uplink: eth1
              access: eth3
            2100:
              state: present
              uplink: eth1
              access: eth4
        AGG20:
          services:
            2000:
              state: present
              uplink: eth1
              access: eth3
            2100:
              state: present
              uplink: eth1
              access: eth4

    PE:
      hosts:
        PE12:
          ansible_host: 172.16.0.112
          router_id: 7.0.0.12
          interface:
            P3_PE12:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.31/31
              interface: 1/1/1
              state: present
            P4_PE12:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.33/31
              interface: 1/1/2
              state: present
          services:
            2000:
              type: vpls
              state: present
              sdp:
                - PE13
                - PE14
              sap: 
                - 1/1/5:2000.*
            2100:
              type: vpls
              state: present
              sdp:
                - PE13
                - PE14
              sap: 
                - 1/1/5:2100.*
            3000:
              type: vprn
              state: present
              interface:
                - name: TO_CE3000-1
                  address: 7.3.0.0/31
                  sap: 1/1/5:3000.0
              static_route:
                - 10.1.0.0/16 next-hop 7.3.0.1
                - 0.0.0.0/0 next-hop 7.3.0.1

        PE13:
          ansible_host: 172.16.0.113
          router_id: 7.0.0.13
          interface:
            P5_PE13:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.35/31
              interface: 1/1/1
              state: present
            P6_PE13:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.37/31
              interface: 1/1/2
              state: present
          services:
            2000:
              type: vpls
              state: present
              sdp:
                - PE12
                - PE14
              sap: 
                - 1/1/5:2000.*
            2100:
              type: vpls
              state: present
              sdp:
                - PE12
                - PE14
              sap: 
                - 1/1/5:2100.*
            3000:
              type: vprn
              state: present
              interface:
                - name: TO_CE3000-2
                  address: 7.3.0.2/31
                  sap: 1/1/5:3000.0
              static_route:
                - 10.2.0.0/16 next-hop 7.3.0.3
        PE14:
          ansible_host: 172.16.0.114
          router_id: 7.0.0.14
          interface:
            P7_PE14:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.39/31
              interface: 1/1/1
              state: present
            P8_PE14:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.41/31
              interface: 1/1/2
              state: present
          services:
            2000:
              type: vpls
              state: present
              sdp:
                - PE12
                - PE13
              sap: 
                - 1/1/5:2000.*
            2100:
              type: vpls
              state: present
              sdp:
                - PE12
                - PE13
              sap: 
                - 1/1/5:2100.*
            3000:
              type: vprn
              state: present
              interface:
                - name: TO_CE3000-3
                  address: 7.3.0.4/31
                  sap: 1/1/5:3000.0
              static_route:
                - 10.3.0.0/16 next-hop 7.3.0.5
            100:
              type: vprn
              state: present
              description: INTERNET

    PEER:
      hosts:
        PEER21:
          router_id: 7.0.0.21
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.21/32
              interface: Loopback0
              state: present
            P1_PEER21:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.43/31
              interface: Ethernet1/0
              state: present
            P2_PEER21:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.45/31
              interface: Ethernet1/1
              state: present
          services:
            100:
              type: vprn
              state: present
              description: INTERNET
              interface:
                - interface: Ethernet1/2
                  ipv4: 1.1.7.21/16
              bgp:
                neighbor:
                  - state: present
                    type: ipv4
                    address: 1.1.2.1
                    as: 2
        PEER22:
          router_id: 7.0.0.22
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.22/32
              interface: Loopback0
              state: present
            P7_PEER22:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.47/31
              interface: Ethernet1/0
              state: present
            P8_PEER22:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.49/31
              interface: Ethernet1/1
              state: present
          services:
            100:
              type: vprn
              state: present
              description: INTERNET
              interface:
                - interface: Ethernet1/2
                  ipv4: 1.1.7.22/16
              bgp:
                neighbor:
                  - state: present
                    type: ipv4
                    address: 1.1.3.1
                    as: 3
              
    P:
      hosts:
        P1:
          router_id: 7.0.0.1
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.1/32
              interface: Loopback0
              state: present
            P1_P2:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.0/31
              interface: Ethernet1/0
              state: present
            P1_P3:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.2/31
              interface: Ethernet1/1
              state: present
            P1_P5:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.4/31
              interface: Ethernet1/2
              state: present
            P1_PEER21:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.42/31
              interface: Ethernet1/3
              state: present
        P2:
          router_id: 7.0.0.2
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.2/32
              interface: Loopback0
              state: present
            P1_P2:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.1/31
              interface: Ethernet1/0
              state: present
            P2_P4:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.6/31
              interface: Ethernet1/1
              state: present
            P2_P6:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.8/31
              interface: Ethernet1/2
              state: present
            P2_PEER21:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.44/31
              interface: Ethernet1/3
              state: present
        P3:
          router_id: 7.0.0.3
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.3/32
              interface: Loopback0
              state: present
            P1_P3:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.3/31
              interface: Ethernet1/1
              state: present
            P3_P4:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.10/31
              interface: Ethernet1/0
              state: present
            P3_P7:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.12/31
              interface: Ethernet1/2
              state: present
            P3_P12:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.30/31
              interface: Ethernet1/3
              state: present
        P4:
          router_id: 7.0.0.4
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.4/32
              interface: Loopback0
              state: present
            P2_P4:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.7/31
              interface: Ethernet1/1
              state: present
            P3_P4:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.11/31
              interface: Ethernet1/0
              state: present
            P4_P8:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.14/31
              interface: Ethernet1/2
              state: present
            P4_P12:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.32/31
              interface: Ethernet1/3
              state: present
        P5:
          router_id: 7.0.0.5
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.5/32
              interface: Loopback0
              state: present
            P1_P5:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.5/31
              interface: Ethernet1/2
              state: present
            P5_P6:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.24/31
              interface: Ethernet1/0
              state: present
            P5_P9:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.26/31
              interface: Ethernet1/1
              state: present
            P5_PE13:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.34/31
              interface: Ethernet1/3
              state: present
        P6:
          router_id: 7.0.0.6
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.6/32
              interface: Loopback0
              state: present
            P2_P6:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.9/31
              interface: Ethernet1/2
              state: present
            P5_P6:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.25/31
              interface: Ethernet1/0
              state: present
            P6_P10:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.28/31
              interface: Ethernet1/1
              state: present
            P5_PE13:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.36/31
              interface: Ethernet1/3
              state: present
        P7:
          router_id: 7.0.0.7
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.7/32
              interface: Loopback0
              state: present
            P3_P7:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.13/31
              interface: Ethernet1/1
              state: present
            P7_P8:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.16/31
              interface: Ethernet1/0
              state: present
            P7_P9:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.18/31
              interface: Ethernet1/2
              state: present
            P7_PE14:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.38/31
              interface: Ethernet1/3
              state: present
            P7_PEER22:
              description: "DOWLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.46/31
              interface: Ethernet1/4
              state: present
        P8:
          router_id: 7.0.0.8
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.8/32
              interface: Loopback0
              state: present
            P4_P8:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.15/31
              interface: Ethernet1/1
              state: present
            P7_P8:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.17/31
              interface: Ethernet1/0
              state: present
            P8_P10:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.20/31
              interface: Ethernet1/2
              state: present
            P8_PE14:
              description: "DOWNLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.40/31
              interface: Ethernet1/3
              state: present
            P8_PEER22:
              description: "DOWLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.48/31
              interface: Ethernet1/4
              state: present
        P9:
          router_id: 7.0.0.9
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.9/32
              interface: Loopback0
              state: present
            P5_P9:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.27/31
              interface: Ethernet1/2
              state: present
            P7_P9:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.19/31
              interface: Ethernet1/1
              state: present
            P9_P10:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.22/31
              interface: Ethernet1/0
              state: present
        P10:
          router_id: 7.0.0.10
          interface:
            Loopback0:
              description: "ISIS"
              ipv4: 7.0.0.10/32
              interface: Loopback0
              state: present
            P6_P10:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.29/31
              interface: Ethernet1/2
              state: present
            P8_P10:
              description: "UPLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.21/31
              interface: Ethernet1/1
              state: present
            P9_P10:
              description: "CROSSLINK;ISIS-L2;LDP"
              ipv4: 10.0.0.23/31
              interface: Ethernet1/0
              state: present