---
#
# https://docs.ansible.com/ansible/latest/modules/ios_interface_module.html#ios-interface-module
#

- name: get interface facts
  iosxr_facts:
    gather_subset: 
      - interfaces
    
- name: remove old ipv4 address
  iosxr_config:
    lines: no ipv4 address
    parents: interface {{ item.value.interface }}
  when: 
    - ansible_net_interfaces[item.value.interface]                        is defined
    - ansible_net_interfaces[item.value.interface]['ipv4'][0]             is defined
    - ansible_net_interfaces[item.value.interface]['ipv4'][0]['address']  is defined
    - ansible_net_interfaces[item.value.interface]['ipv4'][0]['address']  != item.value.ipv4 | ipaddr('address')
  loop: "{{ interface | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: no interface
  iosxr_config:
    lines: 
      - default interface {{ item.value.interface }}
  when:
    - item.value.state == "absent"
  loop: "{{ interface | dict2items }}"

- name: interface
  iosxr_config:
    src: iosxr.j2
  when:
    - item.value.state != "absent"
  loop: "{{ interface | dict2items }}"
  register: output

- set_fact: output_updates={{ output_updates | default([]) + item.commands }}
  when: item.commands is defined
  loop: "{{ output.results }}"
  loop_control:
    label: "{{ item.item.key }}"
    
- name: changes performed
  debug:
    msg: "{{ output_updates }}"
  when: output_updates is defined

  
- name: interface no shut
  iosxr_config:
    lines: 
      - no shutdown
    parents: interface {{ item.key }}
  when:
    - item.value.operstatus == "administratively down"
    - item.value.description is string
  loop: "{{ ansible_net_interfaces | dict2items }}"