---

- name: delete interface address
  include_tasks: junos_delete.yml

- name: configure interface
  junos_config:
    src: junos.j2
    src_format: set
  loop: "{{ interface | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: output

- set_fact: output_updates={{ output_updates | default([]) + item.invocation.module_args['src'].split("\n") }}
  when: item.changed|bool == True
  loop: "{{ output.results }}"
  loop_control:
    label: "{{ item.item.key }}"
    
- name: changes performed
  debug:
    msg: "{{ output_updates }}"
  when: output_updates is defined

