---

- name: save config
  ios_config:
    save_when: modified
  when: 
    - ansible_network_os == "ios"

- name: save config
  sros_config:
    save: yes
  when: 
    - ansible_network_os == "sros"

- name: save config
  vyos_config:
    save: yes
  when: 
    - ansible_network_os == "vyos"