---

- name:          bgp
  include_tasks: "{{ ansible_network_os }}.yml"
  when: 
    - ansible_network_os is defined
    - bgp                is defined
    - bgp.state          != "absent"
