---

- name: configure bgp
  sros_config:
    src: sros.j2
  when: 
    - (bgp.state == "present") or (bgp.state == "changed")
  register: output  
  
- name: changes performed
  debug:
    msg: "{{ output.commands }}"
  when: output.commands is defined
