---

- name:          "{{ ansible_network_os }}"
  include_tasks: "{{ ansible_network_os }}.yml"
  when: 
    - ansible_network_os is defined
    - ldp                is defined
    - ldp.state          != "absent"
