---

- name: LDP
  sros_config:
    src: sros.j2
  when: '"LDP" in item.value.description'
  loop: "{{ interface | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: output

- set_fact: output_updates={{ output_updates | default([]) + item.commands }}
  when: item.commands is defined
  loop: "{{ output.results }}"
  loop_control:
    label: "{{ item.item.key }}"
    
- name: changes performed
  debug:
    msg: "{{ output_updates }}"
  when: output_updates is defined
